name: Feature request
description: Suggest a new feature
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature!

        To help us understand your request better, please fill out the following form.
  - type: textarea
    attributes:
      label: Description
      description: Please describe the feature you'd like to see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: Please describe how this feature would be useful to you.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Priority
      default: "Low"
      options:
        - "Low"
        - "Medium"
        - "High"
  - type: textarea
    attributes:
      label: Additional Information
      description: Any additional context or information you'd like to provide.
